version: "3"
services:
  openvas:
    ports:
      - "9392:9392"
    environment:
      - "PASSWORD=password"
      - "USERNAME=admin"
      - "RELAYHOST=smtp.gmail.com"
      - "SMTPPORT=465"
      - "REDISDBS=512" # number of Redis DBs to use
      - "QUIET=false"  # dump feed sync noise to /dev/null
      - "NEWDB=true"  # only use this for creating a blank DB 
      - "SKIPSYNC=false" # Skips the feed sync on startup.
      - "RESTORE=false"  # This probably not be used from compose... see docs.
      - "DEBUG=false"  # This will cause the container to stop and not actually start gvmd
      - "HTTPS=false"  # wether to use HTTPS or not
      - "GMP=9390"    # to enable see docs
    volumes:
      - "openvas:/data"
    container_name: openvas
    image: immauss/openvas
volumes:
  openvas:
